/*
 * <license header>
 */

import { CustomDialog, CloseButton, Button, Text } from '@react-spectrum/s2';
import AlertDiamond from '@react-spectrum/s2/icons/AlertDiamond';
import CheckmarkCircle from '@react-spectrum/s2/icons/CheckmarkCircle';
import FileText from '@react-spectrum/s2/icons/FileText';
import Download from '@react-spectrum/s2/icons/Download';
import Refresh from '@react-spectrum/s2/icons/Refresh';
import Checkmark from '@react-spectrum/s2/icons/Checkmark';
import { LABELS, formatLabel } from '../../constants/labels';
import {
  dashboardBase,
  dialogTitle,
  dialogDesc,
  generatingLabel,
  generatedNote,
  bannerBody,
  bodyText,
  detailText,
} from './styles';

/** Bytes → "1.2 MB" / "640 KB" (matches the Figma file-size format). */
function formatSize(bytes) {
  if (bytes == null) return '';
  const mb = bytes / (1024 * 1024);
  if (mb >= 1) return `${mb.toFixed(1)} MB`;
  return `${Math.max(1, Math.round(bytes / 1024))} KB`;
}

/**
 * "Pre-read" dialog (opened from the Pre-read header CTA). Three states driven
 * by shared dashboard state: no saved artifact (notice + Go to Artifact), an
 * artifact saved but not yet generated (Generate + disabled Download), and
 * generated (Regenerate + Download + "Generated by …" footnote). UI-only for now.
 */
function PreReadDialog({ savedArtifacts = [], preRead, onCancel, onGoToArtifact, onGenerate, onDownload }) {
  const artifact = savedArtifacts[0];
  const hasArtifact = !!artifact;
  const generated = !!preRead;

  return (
    <CustomDialog size="M" isDismissible padding="none">
      {/* Portal renders outside .es-dashboard — re-apply the sans font. */}
      <div className={`es-preread ${dashboardBase}`}>
        <div className="es-preread__close">
          <CloseButton />
        </div>
        <h2 className={`es-preread__title ${dialogTitle}`}>{LABELS.preread.title}</h2>
        <p className={`es-preread__desc ${dialogDesc}`}>{LABELS.preread.description}</p>

        {!hasArtifact ? (
          <div className="es-preread__notice">
            <span className={`es-preread__notice-text ${bannerBody}`}>{LABELS.preread.noArtifact}</span>
            <AlertDiamond aria-hidden="true" />
          </div>
        ) : (
          <div className="es-preread__source">
            <div className="es-preread__source-head">
              <CheckmarkCircle aria-hidden="true" />
              <span className={generatingLabel}>{LABELS.preread.generatingFrom}</span>
            </div>
            <div className="es-preread__file">
              <FileText aria-hidden="true" />
              <div className="es-preread__file-meta">
                <div className={bodyText}>{artifact.name}</div>
                <div className={detailText}>{formatSize(artifact.size)}</div>
              </div>
            </div>
          </div>
        )}

        <div className="es-preread__footer">
          <Button variant="secondary" fillStyle="outline" onPress={onCancel}>
            {LABELS.preread.cancel}
          </Button>

          {!hasArtifact ? (
            <Button variant="primary" fillStyle="fill" onPress={onGoToArtifact}>
              {LABELS.preread.goToArtifact}
            </Button>
          ) : (
            <>
              <Button variant="primary" fillStyle="fill" onPress={onGenerate}>
                {generated && <Refresh />}
                <Text>{generated ? LABELS.preread.regenerate : LABELS.preread.generate}</Text>
              </Button>
              <Button variant="secondary" fillStyle="outline" isDisabled={!generated} onPress={onDownload}>
                <Download />
                <Text>{LABELS.preread.download}</Text>
              </Button>
            </>
          )}
        </div>

        {generated && (
          <div className={`es-preread__generated ${generatedNote}`}>
            <Checkmark aria-hidden="true" />
            <span>{formatLabel(LABELS.templates.generatedBy, { by: preRead.by, date: preRead.at })}</span>
          </div>
        )}
      </div>
    </CustomDialog>
  );
}

export default PreReadDialog;
